version: '3.8'

services:
  transfer:
    build: .
    image: transfer
    container_name: transfer-container
    restart: always
    ports: 
      - 9001:9001
    volumes:
      - /export/data/logs/:/export/data/logs/
    environment:
      TZ: Asia/Shanghai

networks:
  default:
    name: d-network
