spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_m.hxlc.inner.com:3306/finance_app?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&roundRobinLoadBalance=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      ## https://github.com/brettwooldridge/HikariCP
      ## 连接池名称
      pool-name: transfer-hikari
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 20
      ## 最小空闲连接数量
      minimum-idle: 1
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    cluster:
      nodes:
        172.26.10.197:7001,
        172.26.10.198:7001,
        172.26.10.174:7001,
        172.26.10.162:7001,
        172.26.10.163:7001,
        172.26.10.161:7001
    password: xdegsdtdswqgvd
  pool:
    size: 8
    thread-name-prefix: task-scheduler-pool-
    await-termination-seconds: 60
    waitForTasksToComplete: true

logging:
  level:
    root: info