spring:
  application:
    name: transfer
  profiles:
    active: '@activeProfile@'
  jmx:
    enabled: false
  freemarker:
    check-template-location: false
    cache: false
    charset: UTF-8
    template-loader-path: classpath:/templates/
    content-type: text/html
    suffix: .ftl
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    settings:
      number_format: 0.##
      template_exception_handler: ignore
      classic_compatible: true
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
  cache:
    redis:
     key-prefix: k_transfer
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9001

#mybatis配置
mybatis:
  mapper-locations: classpath:sql_mapper/*.xml
  type-aliases-package: com.bazzi.transfer.model
  configuration:
    call-setters-on-nulls: true
    use-generated-keys: true
    cache-enabled: true
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

#通用mapper配置
mapper:
  mappers: com.bazzi.core.generic.BaseMapper
  not-empty: false
  identity: MYSQL

#PageHelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

logging:
  config: classpath:log4j2-spring.xml
  file:
    path: /export/data/logs
  charset:
    file: UTF-8
    console: UTF-8
